<?php
    function errorClass ($name, $formError)
    {
        if (isset($formError[$name])) {
            return ' error';
        } else {
            return '';
        }
    }
?>
<h2>Group administration</h2>
<form action="?c=group&amp;a=changegroup&amp;groupUri=<?= urlencode($this->groupUri); ?>" method="post" class="form-horizontal">
    <fieldset>
        <legend>Change group informations</legend>
        <div class="control-group<?= errorClass('groupname', $this->formError) ?>">
            <label class="control-label" for="groupname">Group name</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="groupname" id="groupname" value="<?= $this->groupName; ?>">
                <?php if (isset($this->formError['groupname'])) : ?>
                <p class="help-inline">The give group name is empty</p>
                <?php endif; ?>
            </div>
        </div>
        <div class="control-group">
        <label class="control-label" for="description">Description</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="description" id="description" value="<?= $this->description; ?>">
                <?php if (isset($this->formError['description'])) : ?>
                <p class="help-inline">The given description is empty</p>
                <?php endif; ?>
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">Change</button>
        </div>
    </fieldset>
</form>

<form action="?c=group&amp;a=deletegroup" method="post" class="form-horizontal" id="deletegroupform">
    <fieldset>
        <legend>Delete this group</legend>
        <p><strong>Warning:</strong> Deleting the Group can not be undone!</p>
        <div class="form-actions">
            <input type="hidden" name="groupUri" value="<?= htmlentities($this->groupUri); ?>">
            <button class="btn btn-danger" type="submit" id="deletegroupsubmit">Delete</button>
        </div>
    </fieldset>
</form>

<script type="text/javascript">
    $(document).ready(function() {
       $('#deletegroupform').submit(function() {
           var btn = $('#deletegroupsubmit');
           if(btn.text() === 'Delete') {
               btn.empty().text('Confirm deletion!');
               btn.blur();
               return false; 
           }
           return true;
       });
    });
</script>