<?php
    function errorClass ($name, $formError)
    {
        if(isset($formError[$name])) {
            return 'error';
        } else {
            return '';
        }
    }
?>
<h2>Group administration</h2>
<form action="?c=group&amp;a=changegroup" method="post" class="form-horizontal">
<fieldset>
<legend>Editing an existing Group on this Xodx isntance.</legend>
<div class="control-group" <?= errorClass('groupname', $this->formError) ?>">
    <label class="control-label" for="groupname">Group name</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="groupname" id="groupname">
        <?php if(isset($this->formError['groupname'])): ?>
        <p class="help-inline">The give group name is empty</p>
        <?php endif; ?>
    </div>
</div>
<div class="control-group" <?= errorClass('description', $this->formError) ?>>
<label class="control-label" for="description">Description</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="description" id="description">
        <?php if(isset($this->formError['description'])): ?>
        <p class="help-inline">The given description is empty</p>
        <?php endif; ?>
    </div>
</div>
<div class="form-actions">
    <input type="hidden" name="groupUri" value="<?= $_POST['groupUri'] ?>">
    <button class="btn btn-primary" type="submit">Change</button>
</form>
<form action="?c=group&amp;a=deletegroup" method="post" class="form-inline">
    <input type="hidden" name="groupUri" value="<?= $_POST['groupUri'] ?>">
    <button class="btn btn-danger" type="submit">Delete</button>
</form>
</div>
</fieldset>
