<div class="profile row-fluid">
    <div class="span9">
        <h2>Site of <?= $this->groupshowName ?></h2>
        <?php
        if (!empty($this->groupMaker)):
        ?>
        <p>Administrator: <a href="<?= $this->groupMaker; ?>"><?= $this->groupMakerName; ?></a></p>
        <?php
        endif;
        ?>
        <?php
        if (!empty($this->groupDescription)) :
        ?>
        <blockquote>Description: <?= $this->groupDescription ?></blockquote>
        <?php
        endif;
        ?>
        <h3>Activities</h3>
        <ul class="nav nav-pills">
            <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
            <li><a href="#link" data-toggle="tab">Link</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="status">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <textarea placeholder="Write a status note" class="input-block-level" name="content"></textarea>
                    <input type="hidden" name="type" value="Note" />
                    <input type="hidden" name="reply" value=false />
                    <input type="hidden" name="groupUri" value="<?= htmlentities($this->groupUri) ?>" />
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
            <div class="tab-pane" id="link">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <input placeholder="Share a link" class="input-block-level" type="text" name="content" />
                    <input type="hidden" name="type" value="Bookmark" />
                    <input type="hidden" name="reply" value="false" />
                    <input type="hidden" name="groupUri" value="<?= htmlentities($this->groupUri) ?>" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
        </div>
        <?php
            $this->partial(
                'activitystreamgroup.phtml',
                array(
                    'activities' => $this->groupshowActivities,
                    'personUri' => $this->profileshowPersonUri,
                    'personName' => $this->profileshowName
                )
            );
        ?>
    </div>
    <div class="span3">
        <?php
        if (!empty($this->isMaker)) :
        ?>
        <form method="get">  
            <input type="hidden" name="c" value="group" />
            <input type="hidden" name="a" value="changegroup" />
            <input type="hidden" name="groupUri" value="<?= htmlentities($this->groupUri) ?>" />
            <button class="btn btn-block btn-warning" type="submit">Administration</button>
        </form>
        <?php
        else :
        ?>
        <form method="post" action="?c=group&amp;a=leavegroup">  
            <input type="hidden" name="group" value="<?= htmlentities($this->groupUri) ?>" />
            <button class="btn btn-block" type="submit">Leave Group</button>
        </form>
        <?php
        endif;
        ?>
        <?php
            if (!empty($this->groupMembers)) :
                $this->partial(
                        'memberlist.phtml', 
                        array('groupMembers' => $this->groupMembers)
                        );
            endif;
        ?>
    </div>
</div>