<div class="profile row-fluid">
    <div class="span9">
        <h2>Site of <?= $this->groupshowNick ?></h2>
        <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128 img-polaroid" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
        <h3>Activities</h3>
        <ul class="nav nav-pills">
            <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
            <li><a href="#link" data-toggle="tab">Link</a></li>
            <li><a href="#photo" data-toggle="tab">Photo</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="status">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <textarea placeholder="Write a status note" class="input-block-level" name="content"></textarea>
                    <input type="hidden" name="type" value="Note" />
                    <input type="hidden" name="reply" value=false />
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
            <div class="tab-pane" id="link">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <input placeholder="Share a link" class="input-block-level" type="text" name="content" />
                    <input type="hidden" name="type" value="Bookmark" />
                    <input type="hidden" name="reply" value="false" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
            <div class="tab-pane" id="photo">
                <form enctype="multipart/form-data" method="post" action="?c=activity&amp;a=addactivity">
                    <input type="file" name="content"/>
                    <input type="hidden" name="type" value="Photo" />
                    <input type="hidden" name="reply" value=false />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
        </div>
        <?php
            $this->partial(
                'activitystream.phtml',
                array(
                    'activities' => $this->profileshowActivities,
                    'personUri' => $this->profileshowPersonUri,
                    'personName' => $this->profileshowName
                )
            );
        ?>
    </div>
</div>
<?php
    var_dump($this);
?>