<div class="profile row-fluid">
    <div class="span9">
        <h2>Site of <?= $this->groupshowNick ?></h2>
        <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128 img-polaroid" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
        <h3>Activities</h3>
        <?php
            $this->partial(
                'activitystream.phtml',
                array(
                    'activities' => $this->profileshowActivities,
                    'personUri' => $this->profileshowPersonUri,
                    'personName' => $this->profileshowName
                )
            );
        ?>
    </div>
</div>
