<div class="profile row-fluid">
    <div class="span9">
        <h2>Site of <?= $this->groupshowNick ?></h2>
        <h3>Activities</h3>
        <?php
            $this->partial(
                'activitystream.phtml',
                array(
                    'activities' => $this->profileshowActivities,
                    'personUri' => $this->profileshowPersonUri,
                    'personName' => $this->profileshowName
                )
            );
        ?>
    </div>
    <div class="span3">
        <form method="post" action="?c=group&amp;a=joingroup">  
            <input type="hidden" name="group" value="<?= htmlentities($this->groupUri) ?>" />
            <?php if($this->isGuest): ?>
            <button class="btn btn-block disabled" disabled="" type="submit">Join Group</button>
            <?php else: ?>
            <button class="btn btn-block" type="submit">Join Group</button>
            <?php endif ?>
        </form>
    </div>
</div>
